<?php
	require_once('fonctions_ini.php');
	nettoyage();
	ajout_membre("ambroise", "mail.bidon@op.com", "1234", true, "Thomine", "Ambroise", "19", "homme");
	ajout_membre("quentin", "mail.bidon@op.com", "1234", true, "Perrachon", "Quentin", "19", "homme");
	ajout_membre("meri", "mail.bidon@op.fr", "1234", false, "Merigold", "Triss", "25", "femme");
	ajout_membre("Randolph Carter", "mail.bidon@op.fr", "1234", false, "Lovecraft", "Howard Philip", "30", "homme");

	ajout_article("Bienvenue sur notre site","Bonjour, ceci est le premier article du site soul drinkers, j'espère que notre site vous plaira. Il est consacré aux épées maudites dans la fiction et l'histoire et contient déjà quelques articles et comptes. N'hésitez pas à vous créer un compte en plus de ceux déjà crées et de commenter les articles. Bonne navigation!","ambroise", array('bienvenue', 'bonjour'),"Jeudi 1 mai 2014",time(),true,"https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSqY7c5AMypCgBDhPeyfgJ_Ui15n3i725PWa5n14iQdDi3WRsIwo24sTKE", "");

	

	ajout_article("Le cycle d'Elric","Le cycle d'Elric est une série de romans de fantasy commencée en 1972 par Michael Moorcock .Il nous conte les aventures d'Elric, l'empereur en titre de l'île de Melniboné, dans le Multivers. Après avoir dominé le monde pendant des millénaires grâce à sa sorcellerie et à sa cruauté, cette nation s'est refermée sur elle-même. Elric, fils de Sadric LXXXVI, occupe le Trône de Rubis. Il est albinos, sorcier et fin bretteur. Mais de santé fragile : sans les drogues qu'il absorbe à longueur de journée, il ne pourrait tenir debout. Elric est très différent de ses compatriotes melnibonéens : eux sont cruels et intéressés par leur seul plaisir, lui peut être doux et rêve de diriger son peuple avec plus de justice, sans être un pantin manipulé par les Seigneurs du Chaos. Il est l'amant de sa cousine Cymoril et le pire ennemi de son cousin Yyrkoon qui le trouve trop faible pour diriger Melniboné.
Dans le premier roman, Yyrkoon tente de tuer Elric lors d'une bataille navale contre des pirates. Après cet échec, il enlève sa sœur Cymoril et lui jette un sort de sommeil éternel. Pour la sauver, Elric n'aura d'autre choix que celui de s'allier avec Arioch, un des Seigneurs du Chaos de ce plan du Multivers. C'est aussi dans ces pages qu'Elric trouvera Stormbringer, une des deux épées runiques voleuses d'âmes (la seconde étant Mournblade).","quentin", array("Elric", "Stormbringer", "fantasy", "Moorcock","roman","Mournblade"),"Jeudi 1 mai 2014",time(),true,"https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcQCJAbIYUrYHd0Bt9MWHlt2ac80EcUNjtzEabdEUpRVjFi2uFPom9H7SOw", "//www.youtube.com/embed/N-yHay62Pss");

	ajout_article("L'épée maudite saika","Dans l'anime Durarara, Saika est une épée démoniaque avec une personnalité et un amour obsessionnel pour l'humanité. Elle a la capacité de posséder les humains lorsqu'elle les blesse, ceux-ci continue à vivre normallement tout en ayant l'esprit de saika en eux; au moment voulu, elle peut en prendre contrôle. De plus les possédés possèdent également la possibilité de posséder d'autre humains en les blessant et ainsi de suite... On la surnomme également l'éventreur en raison des accidents provoqués par elle au cours de la série.","meri", array("anime", "durarara", "saika", "katana"),"jeudi 1 mai 2014",time(),true,"https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcT7HLbH8nhC9lbt1vMS3IYrgfpC6aJApkDfnJOlYDtakcZy-o2269HeR8g", "");

	ajout_article("La lame d'ébonite","Dans le jeu de rôle the elder scrolls: Skyrim, la lame d'ébonite est un artéfact daedrique qui est offert au Dovahkiin par le prince daedrique Mephala en récompense pour avoir accomplit la quête La porte murmurante qui peut être commencée à partir du niveau 20. Cette arme est une épée à deux mains disposant d'un enchantement d'absorption de 10 points de vie.Cet enchantement peut être amélioré en tuant des PNJ amis (un ami étant un personnage pour lequel vous avez effectué une mission, auquel vous avez accordé une faveur ou quelqu'un que vous avez gagné au cours de n'importe quelle quête). A chaque fois que vous tuez deux amis l'enchantement devient plus puissant et gagne 2 points d'absorption de vie en plus et cela jusqu'à un enchantement d'absorption de 30 points de vie maximum (donc en tuant 10 amis). Une fois cette épée amenée à son plein potentiel elle devient l'une des armes les plus efficaces du jeu en cela qu'elle permet au Dovahkiin de regagner perpétuellement de la vie et surtout que son enchantement ne nécessite pas d'être rechargé. Cette arme bénéficie d'une charge infinie. ","Randolph Carter", array("Skyrim","Bordeciel","elder" ,"scrolls","rpg","daedra","Mephala","katana","lame", "ébonite"),"jeudi 1 mai 2014",time(),true,"http://img1.wikia.nocookie.net/__cb20120407133023/elderscrolls/fr/images/thumb/8/85/Lame_d%27%C3%A9bonite.png/200px-Lame_d%27%C3%A9bonite.png", "//www.youtube.com/embed/z6E4ww5nMYo");

	ajout_article("L'épée Aubéclat","Dans le jeu the elder scrolls: Skyrim, Aubéclat est un artéfact daedrique qui est offert au Dovahkiin par le prince daedrique de la lumière Méridia en récompense pour avoir terminé la quête daedrique associé La lumière de l'aube. Cette épée est une arme à une main disposant d'un enchantement unique appelé le Châtiment de Méridia. La premier enchantement provoque 10 points de dégâts de feu à la cible. Le second enchantement peut provoquer une explosion si la cible des coups du Dovahkiin est tuée. Cette explosion affecte uniquement les morts-vivants proche et les survivants de l'explosion peuvent fuir. De plus il est à noter que cette arme bénéficie d'un nombre anormalement élevé de charges, plus important que la plupart des autres armes enchantées. Par conséquent cette arme nécessite plus qu'une âme sublime pour être totalement rechargée. Bien qu'il existe d'autres épée avec des dégâts plus important, l’enchantement unique de cette épée la rend extrêmement puissante lors des combats contre les mort-vivants spécialement lorsque plusieurs Draugr de bas niveau attaquent en même temps. Ils seront soufflé par l'explosion et s'ils survivent il y a de forte chance qu'ils s'enfuient. Elle est aussi très efficace contre les vampires puisque ces derniers sont considérés comme des mort-vivants par conséquent ils sont également sensible aux explosions de feu. Par ailleurs avec leur vulnérabilité au feu Aubéclat devient la parfaite tueuse de vampire grâce à ses deux enchantements. ","ambroise", array("Skyrim","Bordeciel","elder", "scrolls", "Aubéclat","Méridia","daedra"),"lundi 5 avril 2009",112,true,"http://img1.wikia.nocookie.net/__cb20120310220111/elderscrolls/fr/images/thumb/5/55/Aub%C3%A9clat.png/250px-Aub%C3%A9clat.png", "");

	ajout_article("Les sabres de Muramasa Sengo","Muramasa Sengo était un forgeron de sabres japonais très connu qui fonda sa propre école du même nom au XVIe siècle. On dit souvent que Muramasa, connu pour sa violence de caractère, transmettait cette violence à ses sabres. La croyance dit aussi que ses sabres étaient assoiffés du sang poussant leurs propriétaires à commettre de nombreux crimes ou bien au suicide. Ieyasu Tokugawa ayant été blessé deux fois par les lames de Muramasa, il s'ensuivit l'interdiction de port de ces dernières lors du shogunat. Ce sont ses lames en majorité qui ont été plus tard suriage, re-signées Masamune afin de contourner leur interdiction par le bakufu Tokugawa. Cependant, par la suite, l'aura de Masamune était devenue si grande que de nombreux artisans signèrent leurs lames de ce nom, donnant lieu à de grands problèmes d'authentification et à la légende de l'existence de Masamune. (Le sabre japonais, du conservateur du Victoria and Albert)","Randolph Carter", array("katana", "japon", "Muramasa","sabre"),"mardi 6 avril 2009",112,true,"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTYkkYwqR7NcFtWe3HyIW3uWl6RykHi3CqVwgRdWDh2XlJBYaKl58KnnMo", "");

	ajout_article("Kitetsu","Dans le manga One Piece, Kitetsu est un forgeron qui a créé les sabres maudits de la série des Kitetsu. Il n'a pas encore fait d'apparition mais a été mentionné dans le Chapitre 97 et l'Épisode 49. Kitetsu désigne aussi la série de trois sabres maudits créés par Kitetsu. Chaque sabre fabriqué par Kitetsu, qui sont nommés d'après son nom, sont ensorcelés et apportent la mort à ceux qui les manient, à tel point que plus personne n'utilise ses sabres. Lorsque Ippon Matsu est entré en possession du Sandai Kitetsu, il a craint pour sa vie et l'a mis dans un baril de sabres bon marché. Mais Zoro Roronoa est tombé dessus et Tashigi l'a identifié. Zoro a apprécié le concept de malédiction et a confronté sa chance et la malédiction.

Il a en effet lancé en l'air le Kitetsu, puis a tendu son bras sur la trajectoire. Il semble que sa chance ait surpassé la malédiction puisque le Kitetsu a frôlé son bras avant de se planter dans le sol. Zoro Roronoa semble donc être une exception puisque sa chance surpasse la malédiction. Le Sandai Kitetsu est le seul de ces trois sabres à avoir été vu actuellement. ","luffy", array("manga", "one", "piece", "shonen", "sabres"),"lundi 5 avril 2009",112,true,"http://img3.wikia.nocookie.net/__cb20130924214008/onepiece/fr/images/thumb/0/06/Zoro_tenant_le_Sandai_Kitetsu.png/180px-Zoro_tenant_le_Sandai_Kitetsu.png", "//www.youtube.com/embed/FsTWE5yZOOA");

	
?>
